<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LoaSchedule.Domain/LoaSchedule.Domain.csproj" />
    <ProjectReference Include="../LoaSchedule.Infrastructure/LoaSchedule.Infrastructure.csproj" />
  </ItemGroup>
</Project>
